apiVersion: v1
kind: Config
clusters:
  - name: do-sfo3-k8s-kubeedge-sfo3-master
    cluster:
      server: https://48dd5764-dc92-44c8-ae4e-eed39810efc9.k8s.ondigitalocean.com
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakF5TWpNdwpNalExTURCYUZ3MDBNakF5TWpNd01qUTFNREJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFESmswYjgvbFFhSHJwK29uOUlOcS8wNlpwWGpmeklqUWN0dStoenEwTmFoazkzUFQwQwp2NVVhaTlQTVJkSHp6MVA2bU1RbnRFbXNyUlB2Tkd2MXNpR0k1Z1Q4K2V5UjJ0QWdCVWgzcURVN2thK29DRU5wCmQvbjhoYzR2SnI4cU1yWUR1Q3ZrZE5EN1dtWkdvZkJ4OEhYS3piZUhtcHBVdHplczRzSzNyeXdDd2F5aHYxTTgKVkIzdk50Skc0MEp1ellwd1RyNzYzNTFSalF1RWNRemYzc1V3RUdGMUIrKzVBcGJPY2d0R2NuNmNlUHRtOHMwbgpVbEEvM0JLQU9wNGlqdVlsUnpoSjBWV0YwSERDeHlQbjEzMkxYQndKbGJVTU1TRlBLNC9FbXhVcFJUZjc5ZzBhCllSL3lUaHFod1BEUzlkTFRwMWtySzNoODJtaVYzR3ZoczRXdEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJPbGljZENJcEphWFRacWVFKwpEVXZHWWJYVHJqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFMTHR4SVV4d1dmQStQcHpCcTVQRlQ5WkFLQm0xCnlZSjJIQmMraWtyeFJCc2ZmUFZiWS9xWk5FWnhpYUdpMjFKL01Fb3VlRWd3K1RlcWVJRkJnYTRYb09BRFF3dzQKK3EyeEdLVWc4bHFsa29UdE1IcTVQNFJsZHV4cnRUVTRRQVFOemtEdG9LcnBReWpTMEtsQUpSbEFzemMvNHNNNAprUUNUTWovZDZ3UCtydml3Sk14ODZpSS9XcmtaY05kTWhUQ1NJOGVvYnNxQW9VZlZmUDFoOWIxNmt3MHBmTFowCncrRXR6Y2liS1lKT2tDTUVPYXB6L29FQ3Z6VVBhT3FHaVE5cHE1OTVudkYyUjZOZzgwY21qbXExWmlLcWJlWFoKRG5kY1R2c0p1V213d291UXZ6LytaekJCWG5SYUtIRUVnbk85Rkp4SkVQYUZoMUZwZFYrK25GdTRYQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      insecure-skip-tls-verify: false
users:
  - name: do-sfo3-k8s-kubeedge-sfo3-master-admin
    user:
      token: 424fb17a8ad1853a97a90e441cd9da3a68914b1cbe987060c5d1d97261aa6e94
contexts: []
preferences: {}
current-context: do-sfo3-k8s-kubeedge-sfo3-master
