{{- if and (.Values.cloudCore.service.enable) }}
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.cloudCore.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cloudCore.labels }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
  name: cloudcore
spec:
  type: {{ .Values.cloudCore.service.type }}
  ports:
  - port: 10000
    targetPort: 10000
    name: cloudhub
  - port: 10001
    targetPort: 10001
    name: cloudhub-quic
  - port: 10002
    targetPort: 10002
    name: cloudhub-https
  - port: 10003
    targetPort: 10003
    name: cloudstream
  - port: 10004
    targetPort: 10004
    name: tunnelport
  selector:
  {{- with .Values.cloudCore.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
