kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: service-reader
rules:
- apiGroups: ["devices.kubeedge.io"] # "" indicates the core API group
  resources: ["devices"]
  verbs: ["get", "watch", "list", "patch"]