apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpirelay
  namespace: default
  labels:
    app: relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpirelay
  template:
    metadata:
      labels:
        app: rpirelay
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: node1
      containers:
      - name: rpirelay
        image: matlock08/kubeedge-relay:0.0.1
        command: ["/rpirelay/relay"]
        args: ["--device=relay-instance-01"]
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - name: config-volume
          mountPath: /opt/kubeedge/
      volumes:
      - name: config-volume
        configMap:
          name: device-profile-config-node1
      restartPolicy: Always
