spec:
  ports:
    - name: http
      protocol: TCP
      appProtocol: http
      port: 80
      targetPort: http
      nodePort: 32557
    - name: https
      protocol: TCP
      appProtocol: https
      port: 443
      targetPort: https
      nodePort: 31158
    - name: cloudhub
      protocol: TCP
      port: 10000
      targetPort: 10000
    - name: cloudhubquic
      protocol: TCP
      port: 10001
      targetPort: 10001
    - name: cloudhubhttps
      protocol: TCP
      port: 10002
      targetPort: 10002
    - name: cloudstream
      protocol: TCP
      port: 10003
      targetPort: 10003
    - name: tunnelnode
      protocol: TCP
      port: 10004
      targetPort: 10004
  